spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: product-service-admin
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/admin/product/**
          filters:
            - AdminRoleCheckFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**

        - id: review-service-admin
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/admin/reviews/**
          filters:
            - AdminRoleCheckFilter

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**
          filters:
            - AuthenticationFilter


  application:
    name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/